### ISSUE TITLE
Bootloop after install

### ISSUE THREAD

**Issue by incapdns** [Fede2782/android_kernel_samsung_a34x#1]
I tried to install the compiled kernel but i am in bootloop, what can it be ?

Commands used to build:
```
ln -s /bin/elfedit aarch64-linux-android34-elfedit
ln -s ld aarch64-linux-android34-ld
ln -s llvm-nm aarch64-linux-android34-nm
ln -s llvm-objcopy aarch64-linux-android34-objcopy
ln -s llvm-ar aarch64-linux-android34-ar
ln -s llvm-readelf aarch64-linux-android34-readelf
ln -s llvm-as aarch64-linux-android34-as
ln -s llvm-strip aarch64-linux-android34-strip
ln -s llvm-bolt aarch64-linux-android34-bolt
ln -s llvm-config aarch64-linux-android34-config
ln -s llvm-cfi-verify aarch64-linux-android34-cfi-verify
ln -s llvm-cov aarch64-linux-android34-cfi-cov
ln -s llvm-cxxfilt aarch64-linux-android34-cxxfilt
ln -s llvm-dis aarch64-linux-android34-dis
ln -s llvm-dwarfdump aarch64-linux-android34-dwarfdump
ln -s llvm-dwp aarch64-linux-android34-dwp
ln -s llvm-ifs aarch64-linux-android34-ifs
ln -s llvm-lib aarch64-linux-android34-lib
ln -s llvm-link aarch64-linux-android34-link
ln -s llvm-lipo aarch64-linux-android34-lipo
ln -s llvm-ml aarch64-linux-android34-ml
ln -s llvm-modextract aarch64-linux-android34-modextract
ln -s llvm-objdump aarch64-linux-android34-objdump
ln -s llvm-profdata aarch64-linux-android34-profdata
ln -s llvm-ranlib aarch64-linux-android34-ranlib
ln -s llvm-rc aarch64-linux-android34-rc
ln -s llvm-readobj aarch64-linux-android34-readobj
ln -s llvm-size aarch64-linux-android34-size
ln -s llvm-strings aarch64-linux-android34-strings
ln -s llvm-symbolizer aarch64-linux-android34-symbolizer
ln -s llvm-windres aarch64-linux-android34-windres


export PATH=/root/.local/bin:/root/bin:/usr/share/Modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
export PATH=/android/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

export ARCH=arm64
export KCFLAGS=-w
export LLVM=1
export LLVM_IAS=1
export CFLAGS=-Wno-unused-but-set-variable
export CC=aarch64-linux-android34-clang
export CXX=aarch64-linux-android34-clang++
export CLANG_TRIPLE=aarch64-linux-gnu-
export CROSS_COMPILE=aarch64-linux-android34-
export PLATFORM_VERSION=12

make O=out \
	ARCH=arm64 \
	KCFLAGS=-w \
	LLVM=1 \
	LLVM_IAS=1 \
	CFLAGS=-Wno-unused-but-set-variable \
	CC=aarch64-linux-android34-clang \
	CXX=aarch64-linux-android34-clang++ \
	CLANG_TRIPLE=aarch64-linux-gnu- \
	CROSS_COMPILE=aarch64-linux-android34- a34x_defconfig

make O=out -j$(nproc --all)\
	ARCH=arm64 \
	KCFLAGS=-w \
	LLVM=1 \
	LLVM_IAS=1 \
	CFLAGS=-Wno-unused-but-set-variable \
	CC=aarch64-linux-android34-clang \
	CXX=aarch64-linux-android34-clang++ \
	CLANG_TRIPLE=aarch64-linux-gnu- \
	CROSS_COMPILE=aarch64-linux-android34-
```

Is thre anything incorrect ?

Plz note that aarch64-linux-android34- is the compiled that is in the NDK

[last_kmsg.txt](https://github.com/Fede2782/android_kernel_samsung_a34x/files/15395159/last_kmsg.txt)

**Comment by Fede2782** [comment]
> I tried to install the compiled kernel but i am in bootloop, what can it be ?
> 
> Commands used to build:
> 
> ```
> ln -s /bin/elfedit aarch64-linux-android34-elfedit
> ln -s ld aarch64-linux-android34-ld
> ln -s llvm-nm aarch64-linux-android34-nm
> ln -s llvm-objcopy aarch64-linux-android34-objcopy
> ln -s llvm-ar aarch64-linux-android34-ar
> ln -s llvm-readelf aarch64-linux-android34-readelf
> ln -s llvm-as aarch64-linux-android34-as
> ln -s llvm-strip aarch64-linux-android34-strip
> ln -s llvm-bolt aarch64-linux-android34-bolt
> ln -s llvm-config aarch64-linux-android34-config
> ln -s llvm-cfi-verify aarch64-linux-android34-cfi-verify
> ln -s llvm-cov aarch64-linux-android34-cfi-cov
> ln -s llvm-cxxfilt aarch64-linux-android34-cxxfilt
> ln -s llvm-dis aarch64-linux-android34-dis
> ln -s llvm-dwarfdump aarch64-linux-android34-dwarfdump
> ln -s llvm-dwp aarch64-linux-android34-dwp
> ln -s llvm-ifs aarch64-linux-android34-ifs
> ln -s llvm-lib aarch64-linux-android34-lib
> ln -s llvm-link aarch64-linux-android34-link
> ln -s llvm-lipo aarch64-linux-android34-lipo
> ln -s llvm-ml aarch64-linux-android34-ml
> ln -s llvm-modextract aarch64-linux-android34-modextract
> ln -s llvm-objdump aarch64-linux-android34-objdump
> ln -s llvm-profdata aarch64-linux-android34-profdata
> ln -s llvm-ranlib aarch64-linux-android34-ranlib
> ln -s llvm-rc aarch64-linux-android34-rc
> ln -s llvm-readobj aarch64-linux-android34-readobj
> ln -s llvm-size aarch64-linux-android34-size
> ln -s llvm-strings aarch64-linux-android34-strings
> ln -s llvm-symbolizer aarch64-linux-android34-symbolizer
> ln -s llvm-windres aarch64-linux-android34-windres
> 
> 
> export PATH=/root/.local/bin:/root/bin:/usr/share/Modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
> export PATH=/android/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
> 
> export ARCH=arm64
> export KCFLAGS=-w
> export LLVM=1
> export LLVM_IAS=1
> export CFLAGS=-Wno-unused-but-set-variable
> export CC=aarch64-linux-android34-clang
> export CXX=aarch64-linux-android34-clang++
> export CLANG_TRIPLE=aarch64-linux-gnu-
> export CROSS_COMPILE=aarch64-linux-android34-
> export PLATFORM_VERSION=12
> 
> make O=out \
> 	ARCH=arm64 \
> 	KCFLAGS=-w \
> 	LLVM=1 \
> 	LLVM_IAS=1 \
> 	CFLAGS=-Wno-unused-but-set-variable \
> 	CC=aarch64-linux-android34-clang \
> 	CXX=aarch64-linux-android34-clang++ \
> 	CLANG_TRIPLE=aarch64-linux-gnu- \
> 	CROSS_COMPILE=aarch64-linux-android34- a34x_defconfig
> 
> make O=out -j$(nproc --all)\
> 	ARCH=arm64 \
> 	KCFLAGS=-w \
> 	LLVM=1 \
> 	LLVM_IAS=1 \
> 	CFLAGS=-Wno-unused-but-set-variable \
> 	CC=aarch64-linux-android34-clang \
> 	CXX=aarch64-linux-android34-clang++ \
> 	CLANG_TRIPLE=aarch64-linux-gnu- \
> 	CROSS_COMPILE=aarch64-linux-android34-
> ```
> 
> Is thre anything incorrect ?
> 
> Plz note that aarch64-linux-android34- is the compiled that is in the NDK
> 
> [last_kmsg.txt](https://github.com/Fede2782/android_kernel_samsung_a34x/files/15395159/last_kmsg.txt)

Hi, Please read the wiki for building. https://github.com/Fede2782/android_kernel_samsung_a34x/wiki

If the issue persists open another PR. This kernel source is also for One UI 6.0 and may not work on One UI 6.1 since I'm still waiting the source release from Samsung OSRC team
